labdiscoveryengine/views/login.py
from flask import Blueprint, redirect, session, url_for, request, flash, g
from flask_babel import gettext
from flask_wtf import FlaskForm

from wtforms import StringField
from wtforms import PasswordField
from wtforms import SubmitField
from wtforms import BooleanField
from wtforms.validators import DataRequired

from labdiscoveryengine import db
from labdiscoveryengine.models import User
from labdiscoveryengine.views.utils import render_themed_template
from labdiscoveryengine.utils import lde_config, is_sql_active

login_blueprint = Blueprint('login', __name__)


class LoginForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired()])
    remember_me = BooleanField('Remember Me')


class LogoutForm(FlaskForm):
    pass


@login_blueprint.before_request
def before_request():
    logout_form = LogoutForm()
    g.logout_form = logout_form


@login_blueprint.context_processor
def inject_vars():
    username = session.get('username')
    role = session.get('role')
    return dict(username=username, role=role)


@login_blueprint.route('/', methods=['GET', 'POST'])
def index():
    return render_themed_template('index.html')


@login_blueprint.route('/login', methods=['GET', 'POST'])
def login():

    # If we are already logged in we redirect to the labs screen.
    username = session.get('username')
    role = session.get('role')
    url = request.args.get('url')
    if not url or not url.startswith('/'):
        url = url_for('user.index')

    if username is not None and role is not None:
        return redirect(url)

    form = LoginForm()
    if request.method == 'POST':
        if form.validate_on_submit():
            username = form.username.data 
            password = form.password.data

            if username in lde_config.administrators:
                if lde_config.administrators[username].check_password_hash(password):
                    session['username'] = form.username.data
                    session['role'] = 'admin'
                    session['is_db'] = False
                    return redirect(url)
                
            if username in lde_config.external_users:
                if lde_config.external_users[username].check_password_hash(password):
                    session['username'] = form.username.data
                    session['role'] = 'external'
                    session['is_db'] = False
                    return redirect(url)
            
            if is_sql_active():
                user = db.session.query(User).filter(User.login == username).first()
                if user is not None:
                    if user.check_password(password):
                        session['username'] = form.username.data
                        # It would be possible to allow additional admins in the database
                        # To be decided
                        session['role'] = 'student'
                        session['is_db'] = True
                        return redirect(url)
                
            form.username.errors.append(gettext("Invalid username or password"))
    
    return render_themed_template('login.html', form=form)


@login_blueprint.route('/logout', methods=['POST'])
def logout():
    form = LogoutForm()
    if form.validate_on_submit():
        session.pop('username', None)
        session.pop('role', None)
        # flash('You have been logged out.')
        return redirect(url_for('login.login'))
    else:
        flash('Logout failed. CSRF check failed.')
        return redirect(url_for('user.index'))

labdiscoveryengine/views/user.py
import secrets
from typing import List, Optional
from flask import Blueprint, jsonify, request, session, redirect, url_for, g
from flask_babel import gettext

from sqlalchemy.orm import joinedload

from labdiscoveryengine import get_locale, db
from labdiscoveryengine.models import Group, User
from labdiscoveryengine.scheduling.data import ReservationRequest, ReservationStatus
from labdiscoveryengine.scheduling.sync.web_api import add_reservation, cancel_reservation, get_reservation_status
from labdiscoveryengine.utils import is_sql_active, lde_config
from labdiscoveryengine.views.login import LogoutForm
from labdiscoveryengine.views.utils import render_themed_template

user_blueprint = Blueprint('user', __name__)


@user_blueprint.before_request
def before_request():
    # Check authentication
    username = session.get('username')
    role = session.get('role')
    if username is None or role is None:
        return redirect(url_for('login.login'))

    logout_form = LogoutForm()
    
    g.username = username
    g.role = role
    g.logout_form = logout_form
    g.is_db = session.get('is_db', False)

@user_blueprint.context_processor
def inject_vars():    
    logout_form = g.logout_form
    username = g.username    
    return dict(logout_form=logout_form, username=username)


@user_blueprint.route('/')
def index():
    """
    This is the user index page.
    """
    groups = _get_user_groups_and_labs()   
    return render_themed_template('user/index.html', groups=groups, laboratories=lde_config.laboratories.values(), resources=lde_config.resources)

def _get_user_groups_and_labs():
    laboratories = lde_config.laboratories.values()

    groups = []
    if g.role == 'admin':
        groups.append({
            'name': gettext("All laboratories"),
            'laboratories': laboratories,
            'laboratories_by_identifier': lde_config.laboratories
        })    
    
    if is_sql_active() and g.is_db:
        user = db.session.query(User).filter(User.login == g.username).options(joinedload(User.groups, Group.permissions)).first()
        if user is not None:
            user_groups = list(user.groups)
            user_groups.sort(key=lambda x: x.updated_at, reverse=True)
            for group in user_groups:
                group_laboratories = []
                for permission in group.permissions:
                    if permission.laboratory in lde_config.laboratories:
                        group_laboratories.append(lde_config.laboratories[permission.laboratory])

                groups.append({
                    'name': group.name,
                    'laboratories': group_laboratories,
                    'laboratories_by_identifier': {
                        lab.identifier: lab for lab in group_laboratories
                    },
                })
    return groups

@user_blueprint.route("/api/")
def api():
    return jsonify(success=True)

@user_blueprint.route('/api/reservations/', methods=['POST'])
def create_reservation():
    request_data = request.get_json(force=True, silent=True) or {}
    laboratory: Optional[str] = request_data.get('laboratory')
    if not laboratory:
        return jsonify(success=False, code='invalid-request', message='Missing laboratory'), 400
    
    if laboratory not in lde_config.laboratories:
        # This would usually be a security issue, as external users will know the full list of laboratories (secret or not)
        # However, in 99% of the cases, the LDE host trusts the external system, and it can help debugging distributed systems
        return jsonify(success=False, code='invalid-request', message='Laboratory {laboratory} does not exist'), 400
    
    user_groups = _get_user_groups_and_labs()
    laboratories_by_group = {group['name']: group['laboratories_by_identifier'] for group in user_groups}

    group = request_data.get('group')
    if group not in laboratories_by_group:
        return jsonify(success=False, code='invalid-request', message=f'Group {group} does not exist'), 400
    
    print(laboratories_by_group[group])
    if laboratory not in laboratories_by_group[group]:
        return jsonify(success=False, code='invalid-request', message=f'Laboratory {laboratory} is not in group {group}'), 400

    resources: Optional[str] = request_data.get('resources') or [] # Ok if empty

    for resource in resources:
        if not isinstance(resource, str):
            return jsonify(success=False, code='invalid-request', message=f'Invalid resource (must be string): {resource}'), 400
    
    if not resources:
        # If it adds no resources, it means that all resources are valid
        resources = list(lde_config.laboratories[laboratory].resources)

    features: List[str] = request_data.get('features') or []
    if not isinstance(features, list):
        return jsonify(success=False, code='invalid-request', message='Invalid features (must be list)'), 400
    
    for feature in features:
        if not isinstance(feature, str):
            return jsonify(success=False, code='invalid-request', message=f'Invalid feature (must be string): {feature}'), 400
        
    user_full_name = None
    if is_sql_active() and g.is_db:
        user = db.session.query(User).filter(User.login == g.username).first()
        if user is not None:
            user_full_name = user.full_name
    
    reservation_request = ReservationRequest(
        identifier=secrets.token_urlsafe(),
        group=group,
        laboratory=laboratory,
        resources=resources,
        features=features,
        user_identifier=g.username, 
        user_full_name=user_full_name,
        user_role=g.role,
        back_url=url_for(".index", _external=True) + f"#lab-{laboratory}",
        max_time=lde_config.laboratories[laboratory].max_time,
        locale=get_locale(),
    )

    reservation_status: ReservationStatus = add_reservation(reservation_request=reservation_request)

    return jsonify(success=True, message='Reservation added', **reservation_status.todict())


@user_blueprint.route('/api/reservations/<reservation_id>', methods=['GET'])
def reservation_get(reservation_id: str):
    previous_status = request.args.get("previous_status")
    previous_position = request.args.get("previous_position")
    if previous_position:
        try:
            previous_position = int(previous_position)
        except Exception as err:
            previous_position = None
    
    if previous_status:
        previous_reservation_status = ReservationStatus(status=previous_status, reservation_id=reservation_id, position=previous_position)
    else:
        previous_reservation_status = None

    # Max time is the maximum time the user is willing to wait if the state is the same
    # as the previous state. Otherwise, it does not affect the call and the result is returned
    # immediately
    default_max_time = 20
    try:
        max_time_waiting = float(request.args.get('max_time') or default_max_time)
    except:
        max_time_waiting = default_max_time

    max_time_waiting = min(max_time_waiting, default_max_time) # max_time cannot be higher than default_max_time

    reservation_status = get_reservation_status(g.username, reservation_id, previous_reservation_status=previous_reservation_status, max_time=max_time_waiting)
    if not reservation_status:
        return jsonify(success=False, message='Reservation not found'), 404

    return jsonify(success=True, **reservation_status.todict())

@user_blueprint.route('/api/reservations/<reservation_id>', methods=['DELETE'])
def reservation_delete(reservation_id: str):
    """
    Cancel the reservation
    """
    result = cancel_reservation(g.username, reservation_id)
    return jsonify(success=True, cancelled=result)

labdiscoveryengine/templates/default/user/_base.html
{% extends "default/_base.html" %}

{% block header %}

    {{ super() }}

    <!-- Logged-in Header -->
    <div class="container mb-5">
        <div class="d-flex justify-content-end align-items-center bg-light p-2">
            <span class="me-3">{{ gettext("Logged in as") }} <strong>{{ username }}</strong></span>
            {% if g.role == 'admin' %}
                <a style="margin-right: 1em" class="btn btn-sm btn-outline-secondary" href="{{ url_for('admin.index') }}"><i class="fas fa-gear"></i>&nbsp;{{ gettext("Administration panel") }}</a> 
            {% endif %}
            <form action="{{ url_for('login.logout') }}" method="post">
                {{ logout_form.hidden_tag() }}
                <button type="submit" class="btn btn-outline-secondary btn-sm">
                    <i class="fas fa-sign-out-alt"></i> {{ gettext("Log out") }}
                </button>
            </form>
        </div>

    </div>

{% endblock %}

labdiscoveryengine/templates/default/user/index.html
{% extends "default/user/_base.html" %}

{% block container %}

<div class="col">
    {% if not groups %}
        <div class="alert alert-warning text-center ">
            <p>{{ gettext("You are not part of any group")}}</p>
        </div>
    {% endif %}
    {% for group in groups %}
        <h3>{{ group['name'] }}</h3>
        <br>

        <!-- Set flexbox on the row -->
        <div id="labAccordion" class="row d-flex flex-wrap">
            {% for lab in group['laboratories'] %}
                <div class="col-md-4 col-sm-6 mb-4">
                    <a name="lab-{{ lab.identifier }}"></a>
                    <!-- Add d-flex and flex-column on card -->
                    <div class="card h-100 d-flex flex-column">
                        <div class="card-header bg-primary text-white" style="box-shadow: 0 4px 8px rgba(0,0,0,0.1);">
                            <h2 class="mb-0" style="font-size: 1.2em; font-weight: 600;">
                                <img src="{{ lab.image }}" alt="{{ lab.display_name }} Icon" height="30" style="border: 2px solid white; border-radius: 5px; box-shadow: 0 2px 4px rgba(0,0,0,0.1);">
                                {{ lab.display_name }}
                            </h2>
                        </div>
                        <!-- Add flex-grow-1 specifically to description -->
                        <div class="card-body d-flex flex-column">
                            <p class="flex-grow-1" style="font-size: 0.9em;">{{ lab.description }}</p>
                            <div>
                                <button data-laboratory="{{ lab.identifier }}" data-group="{{ group['name'] }}" class="btn btn-primary btn-sm mb-2 access-btn lab-access-btn" style="font-weight: 600; border-radius: 15px;"><i class="fas fa-arrow-right icon-normal"></i><i class="fas fa-spin fa-spinner icon-spin" style="display: none"></i> <span>{{ gettext("Access") }}</span></button>
                                <p id="message-lab-{{ lab.identifier }}" class="" style="font-size: 0.9em"></p>
                            </div>
                            <div class="mt-2">
                                <a href="#" class="btn btn-link btn-sm toggle-keywords text-decoration-none" data-bs-toggle="collapse" data-bs-target="#keywords{{ loop.index }}"><i class="fas fa-tags"></i> <span>{{ gettext("Keywords") }}</span></a>
                                <a href="#" class="btn btn-link btn-sm toggle-resources text-decoration-none" data-bs-toggle="collapse" data-bs-target="#resources{{ loop.index }}"><i class="fas fa-book"></i> <span>{{ gettext("Resources") }}</span></a>
                                <a href="#" class="btn btn-link btn-sm toggle-features text-decoration-none" data-bs-toggle="collapse" data-bs-target="#features{{ loop.index }}"><i class="fas fa-book"></i> <span>{{ gettext("Features") }}</span></a>
                            </div>
                        </div>

                        <!-- Keywords and Resources -->
                        <div class="flex-grow-0 mx-2">
                            <!-- Keywords -->
                            <div class="collapse mt-2" id="keywords{{ loop.index }}">
                                <h5 style="font-size: 0.8em;">{{ gettext("Keywords:") }}</h5>
                                <ul>
                                    {% for keyword in lab.keywords|sort %}
                                    <li>{{ keyword }}</li>
                                    {% endfor %}
                                </ul>
                            </div>

                            <!-- Resources -->
                            <div class="collapse mt-2" id="resources{{ loop.index }}">
                                <div class="table-responsive">
                                    <table class="table table-sm">
                                        <thead>
                                            <tr>
                                                <th>{{ gettext("Resource") }}</th>
                                                <th>{{ gettext("Features") }}</th>
                                                <th>{{ gettext("Access") }}</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            {% for resource in lab.resources|sort %}
                                            <tr>
                                                <td>{{ resource }}</td>
                                                <td>
                                                    {% if resources[resource].features %}
                                                        {%- for feature in resources[resource].features|sort -%}
                                                            {{ feature }}
                                                            {%- if not loop.last %}, {% endif -%}
                                                        {%- endfor -%}
                                                        {% else %}
                                                        {{ gettext("No feature") }}
                                                    {% endif %}
                                                </td>
                                                <td><button data-laboratory="{{ lab.identifier }}" data-resource="{{ resource }}" data-group="{{ group['name'] }}" class="btn btn-secondary btn-sm access-btn resource-access-btn"><i class="fas fa-download icon-normal"></i><i class="fas fa-spin fa-spinner icon-spin" style="display: none"></i> <span>{{ gettext("Access") }}</span></button></td>
                                            </tr>
                                            {% endfor %}
                                        </tbody>
                                    </table>
                                </div>
                            </div>

                            <!-- Features -->
                            <div class="collapse mt-2" id="features{{ loop.index }}">
                                <h5 style="font-size: 0.8em;">{{ gettext("Features:") }}</h5>
                                
                                {% for feature in lab.features|sort %}
                                <div class="form-check form-check-inline">
                                    <input data-feature="{{ feature }}" class="form-check-input" id="feature-{{ lab.identifier }}-{{ feature }}" name="features-{{ lab.identifier }}" type="checkbox">
                                    <label class="form-check-label" for="feature-{{ lab.identifier }}-{{ feature }}">{{ feature }}</label>
                                </div>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    {% endfor %}
</div>
{% endblock %}

{% block tail %}
<script>
    var ACCESSING_MESSAGE = {{ gettext("Accessing")|tojson }};
    var RESERVE_STARTING_MESSAGE = {{ gettext("Starting reserve process...")|tojson }};
    var RESERVE_WAITING_MESSAGE = {{ gettext("Waiting to be ready...")|tojson }};
    var RESERVE_FINISHED_MESSAGE = {{ gettext("Reservation finished...")|tojson }};  // TO-DO: What is this state?
    var RESERVE_READY_MESSAGE = {{ gettext("Reservation is ready. Redirecting...")|tojson }};
    var RESERVE_QUEUED = {{ gettext("Reservation is queued in position {pos}...")|tojson }};
    var BROKEN_FINISHED_MESSAGE = {{ gettext("Reservation cancelled: no resource was available.")|tojson }};

    var HIDE_KEYWORDS_MESSAGE = {{ gettext("Hide Keywords")|tojson }};
    var KEYWORDS_MESSAGE = {{ gettext("Keywords")|tojson }};

    var HIDE_RESOURCES_MESSAGE = {{ gettext("Hide Resources")|tojson }};
    var RESOURCES_MESSAGE = {{ gettext("Resources")|tojson }};

    var API_URL = {{ url_for(".api")|tojson }};
</script>

<script>
    document.addEventListener("DOMContentLoaded", function() {
      var keywordLinks = document.querySelectorAll('.toggle-keywords');
      var resourceLinks = document.querySelectorAll('.toggle-resources');
    
      keywordLinks.forEach(function(link) {
        var collapseElementId = link.getAttribute("data-bs-target");
        var collapseElement = document.querySelector(collapseElementId);
        var textElement = link.querySelector('span');
    
        collapseElement.addEventListener('show.bs.collapse', function () {
          textElement.textContent = HIDE_KEYWORDS_MESSAGE;
        });
    
        collapseElement.addEventListener('hide.bs.collapse', function () {
          textElement.textContent = KEYWORDS_MESSAGE;
        });
      });
    
      resourceLinks.forEach(function(link) {
        var collapseElementId = link.getAttribute("data-bs-target");
        var collapseElement = document.querySelector(collapseElementId);
        var textElement = link.querySelector('span');
    
        collapseElement.addEventListener('show.bs.collapse', function () {
          textElement.textContent = HIDE_RESOURCES_MESSAGE;
        });
    
        collapseElement.addEventListener('hide.bs.collapse', function () {
          textElement.textContent = RESOURCES_MESSAGE;
        });
      });
    });

    function processGetReservationSuccess (response, laboratory, resource) {
        var messageDomIdentifier;

// The original plan was to have a specific message field for each resource but it doesn't fit all that great so we use only one
// message field (from the lab in general).
//        if (resource === null)
//            messageDomIdentifier = "#message-lab-" + laboratory;
//        else
//            messageDomIdentifier = "#message-resource-" + laboratory + "-" + resource;

        messageDomIdentifier = "#message-lab-" + laboratory;

        var previousState = "?previous_status=" + response.status;
        if (response.status === "ready") {
            $(messageDomIdentifier).text(RESERVE_READY_MESSAGE);
            location.href = response.url;
            return;
        } else if (response.status === "queued") {
            $(messageDomIdentifier).text(RESERVE_QUEUED.replace("{pos}", response.position));
            previousState = previousState + "&previous_position=" + response.position;
        } else if (response.status === "initializing") {
            $(messageDomIdentifier).text(RESERVE_STARTING_MESSAGE);
        } else if (response.status === "pending") {
            $(messageDomIdentifier).text(RESERVE_WAITING_MESSAGE);
        } else if (response.status === "finished") {
            $(messageDomIdentifier).text(RESERVE_FINISHED_MESSAGE);
        } else if (response.status === "broken") {
            $(messageDomIdentifier).text(BROKEN_FINISHED_MESSAGE);
            return;
        } else {
            $(messageDomIdentifier).text(response.status);
        }

        $.ajax({
            url: window.API_URL + "reservations/" + response.reservation_id + previousState,
            type: "GET"
        }).done(function (response) {
            if (response.success) {
                processGetReservationSuccess(response, laboratory, resource);
            } else {
                // TODO
            }
        }).fail(function (response) {
            // TODO
        })
    }
    
    
    $(document).ready(function () {
    
        $(".access-btn").click(function () {

            $(".access-btn").attr("disabled", "disabled");

            // Change the button for an Accessing message with a spinner.
            $(this).find("span").text(ACCESSING_MESSAGE);

            $(this).find(".icon-normal").hide();
            $(this).find(".icon-spin").show();

            var laboratory = $(this).data("laboratory");
            var resource = $(this).data("resource");
            var group = $(this).data("group");

            var features = [];
            $("input[name='features-" + laboratory + "']").each(function() {
                if ($(this).is(":checked")) {
                    features.push($(this).data("feature"));
                }
            });

            var requestData = {
                laboratory: laboratory,
                group: group
            };
            if (resource) {
                requestData['resources'] = [ resource ];
            } else {
                requestData['features'] = features;
                resource = null;
            }

            $.ajax({
                url: window.API_URL + "reservations/",
                type: "POST",
                contentType: "application/json",
                data: JSON.stringify(requestData),
            }).done(function (response) {
                if (response.success) {
                    processGetReservationSuccess(response, laboratory, resource);
                } else {
                    // TODO
                }
            }).fail(function (response) {
                // TODO
            })
        })
    
    });
    
</script>
{% endblock %}