labdiscoveryengine/views/login.py
from flask import Blueprint, redirect, session, url_for, request, flash, g
from flask_babel import gettext
from flask_wtf import FlaskForm

from wtforms import StringField
from wtforms import PasswordField
from wtforms import SubmitField
from wtforms import BooleanField
from wtforms.validators import DataRequired

from labdiscoveryengine import db
from labdiscoveryengine.models import User
from labdiscoveryengine.views.utils import render_themed_template
from labdiscoveryengine.utils import lde_config, is_sql_active

login_blueprint = Blueprint('login', __name__)


class LoginForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired()])
    remember_me = BooleanField('Remember Me')


class LogoutForm(FlaskForm):
    pass


@login_blueprint.before_request
def before_request():
    logout_form = LogoutForm()
    g.logout_form = logout_form


@login_blueprint.context_processor
def inject_vars():
    username = session.get('username')
    role = session.get('role')
    return dict(username=username, role=role)


@login_blueprint.route('/', methods=['GET', 'POST'])
def index():
    return render_themed_template('index.html')


@login_blueprint.route('/login', methods=['GET', 'POST'])
def login():

    # If we are already logged in we redirect to the labs screen.
    username = session.get('username')
    role = session.get('role')
    url = request.args.get('url')
    if not url or not url.startswith('/'):
        url = url_for('user.index')

    if username is not None and role is not None:
        return redirect(url)

    form = LoginForm()
    if request.method == 'POST':
        if form.validate_on_submit():
            username = form.username.data 
            password = form.password.data

            if username in lde_config.administrators:
                if lde_config.administrators[username].check_password_hash(password):
                    session['username'] = form.username.data
                    session['role'] = 'admin'
                    session['is_db'] = False
                    return redirect(url)
                
            if username in lde_config.external_users:
                if lde_config.external_users[username].check_password_hash(password):
                    session['username'] = form.username.data
                    session['role'] = 'external'
                    session['is_db'] = False
                    return redirect(url)
            
            if is_sql_active():
                user = db.session.query(User).filter(User.login == username).first()
                if user is not None:
                    if user.check_password(password):
                        session['username'] = form.username.data
                        # It would be possible to allow additional admins in the database
                        # To be decided
                        session['role'] = 'student'
                        session['is_db'] = True
                        return redirect(url)
                
            form.username.errors.append(gettext("Invalid username or password"))
    
    return render_themed_template('login.html', form=form)


@login_blueprint.route('/logout', methods=['POST'])
def logout():
    form = LogoutForm()
    if form.validate_on_submit():
        session.pop('username', None)
        session.pop('role', None)
        # flash('You have been logged out.')
        return redirect(url_for('login.login'))
    else:
        flash('Logout failed. CSRF check failed.')
        return redirect(url_for('user.index'))

labdiscoveryengine/views/public.py
from flask import Blueprint, current_app
from labdiscoveryengine.utils import lde_config
from labdiscoveryengine.views.utils import render_themed_template

public_blueprint = Blueprint('public', __name__)

@public_blueprint.route('/')
def index():
    """
    This is the public index page.
    """
    if current_app.config['DEFAULT_LAB_VISIBILITY'] == 'private':
        return "The laboratories are not public.", 403
    return render_themed_template('public/index.html', laboratories=lde_config.laboratories.values())

labdiscoveryengine/views/user.py
import secrets
from typing import List, Optional
from flask import Blueprint, jsonify, request, session, redirect, url_for, g
from flask_babel import gettext

from sqlalchemy.orm import joinedload

from labdiscoveryengine import get_locale, db
from labdiscoveryengine.models import Group, User
from labdiscoveryengine.scheduling.data import ReservationRequest, ReservationStatus
from labdiscoveryengine.scheduling.sync.web_api import add_reservation, cancel_reservation, get_reservation_status
from labdiscoveryengine.utils import is_sql_active, lde_config
from labdiscoveryengine.views.login import LogoutForm
from labdiscoveryengine.views.utils import render_themed_template

user_blueprint = Blueprint('user', __name__)


@user_blueprint.before_request
def before_request():
    # Check authentication
    username = session.get('username')
    role = session.get('role')
    if username is None or role is None:
        return redirect(url_for('login.login'))

    logout_form = LogoutForm()
    
    g.username = username
    g.role = role
    g.logout_form = logout_form
    g.is_db = session.get('is_db', False)

@user_blueprint.context_processor
def inject_vars():    
    logout_form = g.logout_form
    username = g.username    
    return dict(logout_form=logout_form, username=username)


@user_blueprint.route('/')
def index():
    """
    This is the user index page.
    """
    groups = _get_user_groups_and_labs()   
    return render_themed_template('user/index.html', groups=groups, laboratories=lde_config.laboratories.values(), resources=lde_config.resources)

def _get_user_groups_and_labs():
    laboratories = lde_config.laboratories.values()

    groups = []
    if g.role == 'admin':
        groups.append({
            'name': gettext("All laboratories"),
            'laboratories': laboratories,
            'laboratories_by_identifier': lde_config.laboratories
        })    
    
    if is_sql_active() and g.is_db:
        user = db.session.query(User).filter(User.login == g.username).options(joinedload(User.groups, Group.permissions)).first()
        if user is not None:
            user_groups = list(user.groups)
            user_groups.sort(key=lambda x: x.updated_at, reverse=True)
            for group in user_groups:
                group_laboratories = []
                for permission in group.permissions:
                    if permission.laboratory in lde_config.laboratories:
                        group_laboratories.append(lde_config.laboratories[permission.laboratory])

                groups.append({
                    'name': group.name,
                    'laboratories': group_laboratories,
                    'laboratories_by_identifier': {
                        lab.identifier: lab for lab in group_laboratories
                    },
                })
    return groups

@user_blueprint.route("/api/")
def api():
    return jsonify(success=True)

@user_blueprint.route('/api/reservations/', methods=['POST'])
def create_reservation():
    request_data = request.get_json(force=True, silent=True) or {}
    laboratory: Optional[str] = request_data.get('laboratory')
    if not laboratory:
        return jsonify(success=False, code='invalid-request', message='Missing laboratory'), 400
    
    if laboratory not in lde_config.laboratories:
        # This would usually be a security issue, as external users will know the full list of laboratories (secret or not)
        # However, in 99% of the cases, the LDE host trusts the external system, and it can help debugging distributed systems
        return jsonify(success=False, code='invalid-request', message='Laboratory {laboratory} does not exist'), 400
    
    user_groups = _get_user_groups_and_labs()
    laboratories_by_group = {group['name']: group['laboratories_by_identifier'] for group in user_groups}

    group = request_data.get('group')
    if group not in laboratories_by_group:
        return jsonify(success=False, code='invalid-request', message=f'Group {group} does not exist'), 400
    
    print(laboratories_by_group[group])
    if laboratory not in laboratories_by_group[group]:
        return jsonify(success=False, code='invalid-request', message=f'Laboratory {laboratory} is not in group {group}'), 400

    resources: Optional[str] = request_data.get('resources') or [] # Ok if empty

    for resource in resources:
        if not isinstance(resource, str):
            return jsonify(success=False, code='invalid-request', message=f'Invalid resource (must be string): {resource}'), 400
    
    if not resources:
        # If it adds no resources, it means that all resources are valid
        resources = list(lde_config.laboratories[laboratory].resources)

    features: List[str] = request_data.get('features') or []
    if not isinstance(features, list):
        return jsonify(success=False, code='invalid-request', message='Invalid features (must be list)'), 400
    
    for feature in features:
        if not isinstance(feature, str):
            return jsonify(success=False, code='invalid-request', message=f'Invalid feature (must be string): {feature}'), 400
        
    user_full_name = None
    if is_sql_active() and g.is_db:
        user = db.session.query(User).filter(User.login == g.username).first()
        if user is not None:
            user_full_name = user.full_name
    
    reservation_request = ReservationRequest(
        identifier=secrets.token_urlsafe(),
        group=group,
        laboratory=laboratory,
        resources=resources,
        features=features,
        user_identifier=g.username, 
        user_full_name=user_full_name,
        user_role=g.role,
        back_url=url_for(".index", _external=True) + f"#lab-{laboratory}",
        max_time=lde_config.laboratories[laboratory].max_time,
        locale=get_locale(),
    )

    reservation_status: ReservationStatus = add_reservation(reservation_request=reservation_request)

    return jsonify(success=True, message='Reservation added', **reservation_status.todict())


@user_blueprint.route('/api/reservations/<reservation_id>', methods=['GET'])
def reservation_get(reservation_id: str):
    previous_status = request.args.get("previous_status")
    previous_position = request.args.get("previous_position")
    if previous_position:
        try:
            previous_position = int(previous_position)
        except Exception as err:
            previous_position = None
    
    if previous_status:
        previous_reservation_status = ReservationStatus(status=previous_status, reservation_id=reservation_id, position=previous_position)
    else:
        previous_reservation_status = None

    # Max time is the maximum time the user is willing to wait if the state is the same
    # as the previous state. Otherwise, it does not affect the call and the result is returned
    # immediately
    default_max_time = 20
    try:
        max_time_waiting = float(request.args.get('max_time') or default_max_time)
    except:
        max_time_waiting = default_max_time

    max_time_waiting = min(max_time_waiting, default_max_time) # max_time cannot be higher than default_max_time

    reservation_status = get_reservation_status(g.username, reservation_id, previous_reservation_status=previous_reservation_status, max_time=max_time_waiting)
    if not reservation_status:
        return jsonify(success=False, message='Reservation not found'), 404

    return jsonify(success=True, **reservation_status.todict())

@user_blueprint.route('/api/reservations/<reservation_id>', methods=['DELETE'])
def reservation_delete(reservation_id: str):
    """
    Cancel the reservation
    """
    result = cancel_reservation(g.username, reservation_id)
    return jsonify(success=True, cancelled=result)

labdiscoveryengine/templates/default/_base.html
<!doctype html>
<html lang="{{ language }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ title }}</title>
    {% assets 'bootstrap_css' %}
        <link href="{{ ASSET_URL }}" rel="stylesheet">
    {% endassets %}
    {% assets 'fontawesome_css' %}
        <link href="{{ ASSET_URL }}" rel="stylesheet">
    {% endassets %}
    {% block head %}{% endblock %}
</head>
<body>

<style>
    /* Make sure the footer sticks to the bottom */
    body {
        display: flex;
        flex-direction: column;
        min-height: 100vh;
    }

    .container {
        flex: 1;
    }

    .footer {
        background-color: #333;
        color: white;
        padding: 20px 0;
        text-align: center;
        position: relative;
    }

    .footer .copyright {
        font-size: 16px;
        font-weight: bold;
        margin-bottom: 10px;
    }

    .footer .funding-info {
        font-size: 12px;
    }

    .footer .logos {
        display: flex;
        justify-content: center;
    }

    .footer img {
        height: 30px;
        margin: 0 10px;
    }
</style>

{% block header %}
    <header style="background-color: white; padding: 10px" class="mb-5">
        <div class="container">
            <div style="display: flex; justify-content: space-between; align-items: center;">
                <a href="https://labdiscoveryengine.labsland.com" target="_blank">
                    <img src="{{ url_for('static', filename='images/labdiscoveryengine.png') }}"
                         alt="LabDiscoveryEngine logo" height="100">
                </a>
                <a href="{{ config['INSTITUTION_URL'] }}" target="_blank">
                    <img src="{{ config['INSTITUTION_LOGO'] }}" alt="{{ config['INSTITUTION_NAME'] }}" height="100">
                </a>
            </div>
        </div>
    </header>
{% endblock %}

{% block body %}
    <div class="container">
        {% block container %}
        {% endblock %}
    </div>
{% endblock %}

{% block footer %}
    <footer class="footer mt-5">
        <div class="container text-center">
            <div class="row">
                    {% for lang_code, language in list_languages().items() %}
                    <div class="col">
                        <a class="btn btn-small btn-outline-secondary" href="{{ url_for(request.endpoint, locale=lang_code) }}">{{ language }}</a>
                    </div>
                    {% endfor %}
            </div>
            <br>
            <div class="copyright">
                Copyright &copy; LabDiscoveryEngine Team
            </div>
            <div class="logos mt-1">
                <img style="margin-left: 70px" class="mh-2" src="{{ url_for('static', filename='images/eu-logo.jpg') }}" alt="EU Logo">
                <img style="padding-left: 100px" src="{{ url_for('static', filename='images/ngi-search-logo.png') }}" alt="NGI Search Logo">
            </div>
            <div class="funding-info">
                Funded by the European Union. Views and opinions expressed are however those of the author(s) only and
                do not necessarily reflect those of the European Union or European Commission. Neither the European
                Union nor the granting authority can be held responsible for them. Funded within the framework of the
                NGI Search project under grant agreement No 101069364.
            </div>
        </div>
    </footer>
{% endblock %}

{% assets 'bootstrap_js' %}
    <script src="{{ ASSET_URL }}"></script>
{% endassets %}

{% assets 'fontawesome_js' %}
    <script src="{{ ASSET_URL }}"></script>
{% endassets %}

{% assets 'vendor_js' %}
    <script src="{{ ASSET_URL }}"></script>
{% endassets %}

{% block tail %}{% endblock %}
</body>
</html>

labdiscoveryengine/templates/default/index.html
{% extends "default/_base.html" %}

{% block container %}
    <h1 class="text-center mb-5" style="font-size: 2.5em; font-weight: bold;">{{ config['INSTITUTION_NAME'] }}'s Lab Discovery Engine</h1>


    <!-- Institution Information -->
    <div class="row mb-5">
        <div class="col-12">
            <div class="card text-center">
                <div class="card-body">
                    <img src="{{ config['INSTITUTION_LOGO'] }}" alt="{{ config['INSTITUTION_NAME'] }}" height="100" class="mb-3">
                    <h5 class="card-title">{{ config['INSTITUTION_NAME'] }}</h5>
                    <p class="card-text">{{ config['INSTITUTION_DESCRIPTION'] }}</p>
                </div>
            </div>
        </div>
    </div>


    <div class="row mb-5">
        <!-- Option 1 -->
        <div class="col-md-6 mb-5">
            <div class="card text-center" style="padding: 20px;">
                <div class="card-header">
                    <i class="fas fa-rocket fa-2x"></i>
                </div>
                <div class="card-body">
                    <h5 class="card-title">{{ gettext("Learn about LabDiscoveryEngine") }}</h5>
                    <p class="card-text">{{ gettext("Explore the main website to find out more about Lab Discovery Engine.") }}</p>
                    <a href="https://labdiscoveryengine.labsland.com" class="btn btn-secondary" target="_blank">{{ gettext("Learn More") }}</a>
                </div>
            </div>
        </div>

        <!-- Option 2 -->
        <div class="col-md-6 mb-5">
            <div class="card text-center" style="padding: 20px;">
                <div class="card-header">
                    <i class="fas fa-user-lock fa-2x"></i>
                </div>
                <div class="card-body">
                    <h5 class="card-title">{{ gettext("Access Laboratories") }}</h5>

                    {% if username %}
                        <p class="card-text">{{ gettext("Access the labs provided by this LabDiscoveryEngine instance.") }}</p>
                        <a href="{{ url_for('user.index') }}" class="btn btn-primary">{{ gettext("Access") }}</a>
                    {% else %}
                        <p class="card-text">{{ gettext("Login to access the labs provided by this LabDiscoveryEngine instance.") }}</p>
                        <a href="{{ url_for('login.login') }}" class="btn btn-primary">{{ gettext("Sign in") }}</a>
                    {% endif %}

                </div>
            </div>
        </div>

            <!-- Public Laboratories -->
        <div class="col-12 mb-5">
            <div class="card text-center" style="padding: 20px;">
                <div class="card-header">
                    <i class="fas fa-flask fa-2x"></i>
                </div>
                <div class="card-body">
                    <h5 class="card-title">{{ gettext("Published Laboratories List") }}</h5>
                    <p class="card-text">{{ gettext("Explore the labs offered by this instance.") }}</p>
                    <a href="{{ url_for('public.index') }}" class="btn btn-info">{{ gettext("View labs")}}</a>
                </div>
            </div>
        </div>

    </div>
{% endblock %}

labdiscoveryengine/templates/default/login.html
{% extends "default/_base.html" %}

{% block container %}
    <div class="row">

        <div class="col col-md-6 offset-md-3 mt-5">

            <h1 class="mb-5">
            {{ gettext("Log in") }}
            </h1>

            <form method="POST" action="{{ url_for('.login', **request.args) }}">
                {{ form.csrf_token }}
                <div class="mb-3">
                    <label for="username" class="form-label">{{ gettext("Username") }}</label>
                    <input class="form-control" name="{{ form.username.id }}" autofocus>
                    {% if form.username.errors %}
                        <div class="alert alert-danger mt-2">
                        {% for error in form.username.errors %}
                            {{ error }}
                        {% endfor %}
                        </div>
                    {% endif %}
                </div>
                <div class="mb-3">
                    <label for="password" class="form-label">{{ gettext("Password") }}</label>
                    <input type="password" class="form-control" name="{{ form.password.id }}">
                    {% if form.password.errors %}
                        <div class="alert alert-danger mt-2">
                        {% for error in form.password.errors %}
                            {{ error }}
                        {% endfor %}
                        </div>
                    {% endif %}
                </div>
                <button type="submit" class="btn btn-primary">{{ gettext("Sign in")}}</button>
            </form>
        </div>

    </div>

{% endblock %}